name: Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - coverage.svg
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  issues: write
  actions: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.ref == 'refs/heads/main' }}
    steps:
      - name: Get job ID
        id: job_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          JOB_ID=$(gh api \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
            --jq '[.jobs[] | select(.status=="in_progress")][0].id')
          echo "job_id=$JOB_ID" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-docs

      - name: Install docs dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --with docs --no-root

      - name: Build site
        run: poetry run task build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Workflow failure notification
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          JOB_ID: ${{ steps.job_id.outputs.job_id }}
          WORKFLOW_NAME: ${{ github.workflow }}
        with:
          filename: .github/failure.md

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
